// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "dynamic.proto" (package "bilibili.app.dynamic.v2", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { Dynamic } from "./dynamic";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { DynDetailReply } from "./dynamic";
import type { DynDetailReq } from "./dynamic";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * v2动态, rpc 按字母顺序排列
 *
 * @generated from protobuf service bilibili.app.dynamic.v2.Dynamic
 */
export interface IDynamicClient {
    /**
     * 动态详情页
     *
     * @generated from protobuf rpc: DynDetail
     */
    dynDetail(input: DynDetailReq, options?: RpcOptions): UnaryCall<DynDetailReq, DynDetailReply>;
}
/**
 * v2动态, rpc 按字母顺序排列
 *
 * @generated from protobuf service bilibili.app.dynamic.v2.Dynamic
 */
export class DynamicClient implements IDynamicClient, ServiceInfo {
    typeName = Dynamic.typeName;
    methods = Dynamic.methods;
    options = Dynamic.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * 动态详情页
     *
     * @generated from protobuf rpc: DynDetail
     */
    dynDetail(input: DynDetailReq, options?: RpcOptions): UnaryCall<DynDetailReq, DynDetailReply> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<DynDetailReq, DynDetailReply>("unary", this._transport, method, opt, input);
    }
}
